// Code generated by MockGen. DO NOT EDIT.
// Source: services/statsAPI/client.go

// Package mock_statsapi is a generated GoMock package.
package mock_statsapi

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	scheduler "github.com/mlb/mlb-ballpark-segregation-service/front_service/gen/scheduler"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetStatsAPISchedule mocks base method.
func (m *MockClient) GetStatsAPISchedule(arg0 context.Context, arg1 string) (*scheduler.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatsAPISchedule", arg0, arg1)
	ret0, _ := ret[0].(*scheduler.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatsAPISchedule indicates an expected call of GetStatsAPISchedule.
func (mr *MockClientMockRecorder) GetStatsAPISchedule(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatsAPISchedule", reflect.TypeOf((*MockClient)(nil).GetStatsAPISchedule), arg0, arg1)
}
